/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cloud_logic_custom": [
        {
            "name": "backend",
            "endpoint": "https://ulqor1kmea.execute-api.eu-west-1.amazonaws.com/bubikb",
            "region": "eu-west-1"
        }
    ],
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_JFzsT9H46",
    "aws_user_pools_web_client_id": "4qfi62r444mat34eg7r5j5upe8",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_content_delivery_bucket": "hackathonapp-20240309030929-hostingbucket-bubikb",
    "aws_content_delivery_bucket_region": "eu-west-1",
    "aws_content_delivery_url": "https://d268jxtdvzl6ny.cloudfront.net"
};


export default awsmobile;
